name: Deploy to GitHub Pages

on:
  push:
    branches: [xin]

jobs:
  deploy-to-pages:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9, "3.10"]
        # Manually specify one OSX + Windows build to make sure it works there.
        include:
          - python-version: "3.10"
            dev: true
          - os: macos-latest
            python-version: "3.9"
          - os: windows-latest
            python-version: "3.9"

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetch all history so that last modified date-times are accurate

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v12
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[coverage]
          python -m pip install --upgrade pip
          python -m pip install invoke
          invoke init

      # - name: 👷‍ Install Dot and pandoc
      #   run: |
      #     conda install -c conda-forge pandoc
      #     conda install -c conda-forge ipython
      #     pip install sphinxcontrib-websupport
      #     sudo apt update
      #     sudo apt install -y graphviz

      - name: 🔧 Build HTML
        run: |
          invoke docs

      - name: 🚀 Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output/html/
